### ISSUE TITLE
.NET 4.5+ compatibiltiy

### ISSUE THREAD

**Issue by glovesave** [nla-brandonjames/ShipStation4Net#11]
It seems that I am not able to use this project in a .NET 4.5.1 project. Do you plan on releasing an update that will be supported in .NET 4.5+?

**Comment by nla-brandonjames** [comment]
I didn't have any plans to support .NET 4.5+. I had actually thought .NET Standard would work on it too. I'm a solo developer at a small business and it's hard enough just supporting this library. I have a few others that I haven't even updated lately because there is no interest in them from the open source community. I have some important progress I need to make on ops applications for my business to progress more than to update the libraries I created for them to work. If you could contribute to this application to move it forward to also support the .NET 4.5.1 assembly, then you are free to contribute to this library!

**Comment by mynkow** [comment]
I can quickly add support for net 4.6.1

Just ping me if this fits in the lib vision

**Comment by nla-brandonjames** [comment]
I think to support .NET 4.5.* you have to dial back the .NET Standard API to v1.3. A dependency I am using (Microsoft.Extensions.Logging) is dependent on .NET Standard 2.0 and would have to be changed to back-support .NET Standard 1.3. I actually don't know how to access the logging feature myself so I haven't been using it even though I have accessed the logging API via my library. If we find a suitable replacement for logging functionality on .NET Standard 1.3 then it will work on .NET fx 4.5.*.

**Comment by mynkow** [comment]
Yeah, I know. However I am talking about 4.6.1 which is one line in the csproj file. As of today, when you reference a `netstandard2.0` in 4.6.1 you may get strange behavior. To get full support you need to have 4.7.1 which was released recently. In order to avoid all headaches usually I add `net461` in my project files so that the nuget contains the two monikiers.

https://github.com/Elders/Cronus/blob/release-4.0.0/src/Elders.Cronus/Elders.Cronus.csproj#L3

See dependencies here => https://www.nuget.org/packages/Cronus/4.0.0-beta0007

**Comment by nla-brandonjames** [comment]
Solved in PR #13. Now the package has been uploaded to NuGet.
